# Generated by Django 5.2.17 on 2026-08-28 20:57

import catalog.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_toman', models.PositiveIntegerField()),
                ('source_name', models.CharField(max_length=160)),
                ('source_url', models.URLField(blank=True)),
                ('quoted_at', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_demo', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-quoted_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=160)),
                ('name_en', models.CharField(max_length=160)),
                ('city_fa', models.CharField(max_length=120)),
                ('city_en', models.CharField(max_length=120)),
                ('mobile_number', models.CharField(max_length=16)),
                ('address_fa', models.TextField(blank=True)),
                ('address_en', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('city', 'City'), ('weave', 'Weave'), ('material', 'Material'), ('color', 'Color'), ('pattern', 'Pattern'), ('brand', 'Brand')], max_length=20)),
                ('code', models.SlugField(max_length=80)),
                ('label_fa', models.CharField(max_length=120)),
                ('label_en', models.CharField(max_length=120)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('category', 'sort_order', 'label_fa'),
                'constraints': [models.UniqueConstraint(fields=('category', 'code'), name='unique_reference_code_per_category')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title_fa', models.CharField(max_length=180)),
                ('title_en', models.CharField(max_length=180)),
                ('description_fa', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('price_toman', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('length_cm', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('width_cm', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('rug_type', models.CharField(choices=[('handmade', 'Handmade'), ('machine', 'Machine-made')], max_length=16)),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used')], max_length=8)),
                ('approximate_age_years', models.PositiveIntegerField(default=0)),
                ('inventory_status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold')], default='available', max_length=16)),
                ('raj', models.PositiveIntegerField(blank=True, null=True)),
                ('reeds', models.PositiveIntegerField(blank=True, null=True)),
                ('density', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='brand_products', to='catalog.referenceitem')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='city_products', to='catalog.referenceitem')),
                ('colors', models.ManyToManyField(related_name='color_products', to='catalog.referenceitem')),
                ('materials', models.ManyToManyField(related_name='material_products', to='catalog.referenceitem')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pattern_products', to='catalog.referenceitem')),
                ('weave', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weave_products', to='catalog.referenceitem')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.store')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=catalog.models.product_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('alt_fa', models.CharField(blank=True, max_length=220)),
                ('alt_en', models.CharField(blank=True, max_length=220)),
                ('is_cover', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_cover', True)), fields=('product',), name='one_cover_image_per_product')],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['inventory_status', 'deleted_at'], name='catalog_pro_invento_a2b163_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['rug_type', 'inventory_status'], name='catalog_pro_rug_typ_0e7a04_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price_toman'], name='catalog_pro_price_t_ab8ae7_idx'),
        ),
    ]
