# Generated by Django 5.2.17 on 2026-09-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_database_architecture'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='referenceitem',
            name='reference_valid_category',
        ),
        migrations.AlterField(
            model_name='referenceitem',
            name='category',
            field=models.CharField(choices=[('province', 'Province'), ('city', 'City'), ('weave', 'Weave'), ('material', 'Material'), ('color', 'Color'), ('pattern', 'Pattern'), ('brand', 'Brand')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='referenceitem',
            constraint=models.CheckConstraint(condition=models.Q(('category__in', ('province', 'city', 'weave', 'material', 'color', 'pattern', 'brand'))), name='reference_valid_category'),
        ),
    ]
