# Generated by Django 5.2.17 on 2026-09-05 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_referenceitem_reference_valid_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='domain',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='store',
            name='manager_mobile_number',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.CreateModel(
            name='StoreBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=120)),
                ('name_en', models.CharField(max_length=120)),
                ('address_fa', models.TextField()),
                ('address_en', models.TextField()),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='catalog.store')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
                'indexes': [models.Index(fields=['store', 'is_active', 'sort_order'], name='store_branch_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('store', 'sort_order'), name='unique_store_branch_order')],
            },
        ),
    ]
