# Generated by Django 5.2.17 on 2026-08-28 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('market_viewed', 'Market viewed'), ('search_performed', 'Search performed'), ('filter_applied', 'Filter applied'), ('sort_changed', 'Sort changed'), ('product_card_clicked', 'Product card clicked'), ('product_viewed', 'Product viewed'), ('contact_clicked', 'Contact clicked'), ('phone_call_clicked', 'Phone call clicked'), ('gallery_interacted', 'Gallery interacted')], max_length=32)),
                ('session_id', models.UUIDField(db_index=True)),
                ('language', models.CharField(choices=[('fa', 'Persian'), ('en', 'English')], max_length=2)),
                ('query', models.CharField(blank=True, max_length=300)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analytics_events', to='catalog.product')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='analytics_a_event_t_6c35be_idx'), models.Index(fields=['product', 'event_type', 'created_at'], name='analytics_a_product_98118c_idx'), models.Index(fields=['session_id', 'product', 'event_type'], name='analytics_a_session_1e6f21_idx')],
            },
        ),
    ]
