# Generated by Django 5.2.17 on 2026-09-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_store_scoped_events'),
        ('catalog', '0005_store_domain_store_manager_mobile_number_storebranch'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='analyticsevent',
            name='analytics_valid_event_type',
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='event_type',
            field=models.CharField(choices=[('market_viewed', 'Market viewed'), ('search_performed', 'Search performed'), ('filter_applied', 'Filter applied'), ('sort_changed', 'Sort changed'), ('product_card_clicked', 'Product card clicked'), ('product_viewed', 'Product viewed'), ('contact_clicked', 'Contact clicked'), ('phone_call_clicked', 'Phone call clicked'), ('gallery_interacted', 'Gallery interacted'), ('sell_flow_started', 'Sell flow started'), ('sell_step_completed', 'Sell step completed'), ('sell_request_submitted', 'Sell request submitted')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='analyticsevent',
            constraint=models.CheckConstraint(condition=models.Q(('event_type__in', ('market_viewed', 'search_performed', 'filter_applied', 'sort_changed', 'product_card_clicked', 'product_viewed', 'contact_clicked', 'phone_call_clicked', 'gallery_interacted', 'sell_flow_started', 'sell_step_completed', 'sell_request_submitted'))), name='analytics_valid_event_type'),
        ),
    ]
