# Generated by Django 5.2.17 on 2026-09-05 16:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import sell_requests.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_remove_referenceitem_reference_valid_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('tracking_code', models.CharField(editable=False, max_length=11, unique=True)),
                ('rug_type', models.CharField(choices=[('handmade', 'Handmade'), ('machine', 'Machine-made')], max_length=16)),
                ('phone_number', models.CharField(db_index=True, max_length=11)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('length_cm', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2000)])),
                ('width_cm', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2000)])),
                ('condition', models.CharField(blank=True, choices=[('new', 'New'), ('used', 'Used')], max_length=8)),
                ('approximate_age_years', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(250)])),
                ('raj', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(150)])),
                ('reeds', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2000)])),
                ('density', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5000)])),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('status', models.CharField(choices=[('needs_review', 'Needs review'), ('in_progress', 'In progress'), ('purchased', 'Purchased'), ('rejected', 'Rejected')], default='needs_review', max_length=16)),
                ('rejection_reason', models.CharField(blank=True, choices=[('condition_mismatch', 'Condition is not suitable'), ('outside_scope', 'Outside purchase scope'), ('duplicate', 'Duplicate request'), ('owner_withdrew', 'Owner withdrew'), ('unable_to_contact', 'Unable to contact owner'), ('other', 'Other')], max_length=32)),
                ('rejection_note', models.TextField(blank=True, max_length=1000)),
                ('utm_source', models.CharField(blank=True, max_length=255)),
                ('utm_medium', models.CharField(blank=True, max_length=255)),
                ('utm_campaign', models.CharField(blank=True, max_length=255)),
                ('utm_term', models.CharField(blank=True, max_length=255)),
                ('utm_content', models.CharField(blank=True, max_length=255)),
                ('first_admin_action_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='brand_sell_requests', to='catalog.referenceitem')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='city_sell_requests', to='catalog.referenceitem')),
                ('colors', models.ManyToManyField(blank=True, related_name='color_sell_requests', to='catalog.referenceitem')),
                ('materials', models.ManyToManyField(blank=True, related_name='material_sell_requests', to='catalog.referenceitem')),
                ('pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pattern_sell_requests', to='catalog.referenceitem')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='province_sell_requests', to='catalog.referenceitem')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sell_requests', to='catalog.store')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SellRequestAdminAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('viewed', 'Viewed'), ('call_clicked', 'Call clicked'), ('note_added', 'Note added'), ('status_changed', 'Status changed')], max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sell_request_actions', to=settings.AUTH_USER_MODEL)),
                ('sell_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions', to='sell_requests.sellrequest')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SellRequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=sell_requests.models.sell_request_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png', 'webp'))])),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sell_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sell_requests.sellrequest')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SellRequestNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sell_request_notes', to=settings.AUTH_USER_MODEL)),
                ('sell_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='sell_requests.sellrequest')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SellRequestStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('needs_review', 'Needs review'), ('in_progress', 'In progress'), ('purchased', 'Purchased'), ('rejected', 'Rejected')], max_length=16)),
                ('to_status', models.CharField(choices=[('needs_review', 'Needs review'), ('in_progress', 'In progress'), ('purchased', 'Purchased'), ('rejected', 'Rejected')], max_length=16)),
                ('rejection_reason', models.CharField(blank=True, choices=[('condition_mismatch', 'Condition is not suitable'), ('outside_scope', 'Outside purchase scope'), ('duplicate', 'Duplicate request'), ('owner_withdrew', 'Owner withdrew'), ('unable_to_contact', 'Unable to contact owner'), ('other', 'Other')], max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sell_status_changes', to=settings.AUTH_USER_MODEL)),
                ('sell_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='sell_requests.sellrequest')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='sellrequest',
            index=models.Index(fields=['store', 'status', 'created_at'], name='sell_store_status_time_idx'),
        ),
        migrations.AddIndex(
            model_name='sellrequest',
            index=models.Index(fields=['store', 'rug_type', 'created_at'], name='sell_store_type_time_idx'),
        ),
        migrations.AddIndex(
            model_name='sellrequest',
            index=models.Index(fields=['store', 'province', 'created_at'], name='sell_store_prov_time_idx'),
        ),
        migrations.AddIndex(
            model_name='sellrequest',
            index=models.Index(fields=['store', 'phone_number'], name='sell_store_phone_idx'),
        ),
        migrations.AddConstraint(
            model_name='sellrequest',
            constraint=models.CheckConstraint(condition=models.Q(('rug_type__in', ('handmade', 'machine'))), name='sell_valid_rug_type'),
        ),
        migrations.AddConstraint(
            model_name='sellrequest',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('needs_review', 'in_progress', 'purchased', 'rejected'))), name='sell_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='sellrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('length_cm__isnull', True), ('width_cm__isnull', True)), models.Q(('length_cm__isnull', False), ('width_cm__isnull', False)), _connector='OR'), name='sell_dimensions_together'),
        ),
        migrations.AddConstraint(
            model_name='sellrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('brand__isnull', True), ('density__isnull', True), ('reeds__isnull', True), ('rug_type', 'handmade')), models.Q(('raj__isnull', True), ('rug_type', 'machine')), _connector='OR'), name='sell_type_fields_match'),
        ),
        migrations.AddConstraint(
            model_name='sellrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('rejection_reason__in', ('condition_mismatch', 'outside_scope', 'duplicate', 'owner_withdrew', 'unable_to_contact', 'other')), ('status', 'rejected')), models.Q(models.Q(('status', 'rejected'), _negated=True), ('rejection_note', ''), ('rejection_reason', '')), _connector='OR'), name='sell_rejection_matches_status'),
        ),
        migrations.AddIndex(
            model_name='sellrequestadminaction',
            index=models.Index(fields=['sell_request', 'action', 'created_at'], name='sell_action_type_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='sellrequestimage',
            constraint=models.UniqueConstraint(fields=('sell_request', 'sort_order'), name='unique_sell_image_order'),
        ),
        migrations.AddConstraint(
            model_name='sellrequestimage',
            constraint=models.CheckConstraint(condition=models.Q(('sort_order__gte', 0), ('sort_order__lte', 3)), name='sell_image_order_range'),
        ),
        migrations.AddIndex(
            model_name='sellrequeststatushistory',
            index=models.Index(fields=['sell_request', 'created_at'], name='sell_history_time_idx'),
        ),
    ]
